
version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tpa
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  api:
    build: ./apps/api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      PORT: ${API_PORT:-4000}
      PAYMENTS_PROVIDER: ${PAYMENTS_PROVIDER}
      HELCIM_API_BASE: ${HELCIM_API_BASE}
      HELCIM_API_TOKEN: ${HELCIM_API_TOKEN}
      HELCIM_ACCOUNT_ID: ${HELCIM_ACCOUNT_ID}
      HELCIM_WEBHOOK_SECRET: ${HELCIM_WEBHOOK_SECRET}
    ports: ["4000:4000"]
    depends_on: [db, redis]
  web:
    build: ./apps/web
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      PORT: ${WEB_PORT:-3000}
    ports: ["3000:3000"]
    depends_on: [api]
